#micronaut:
  #application:
    #name: crud

micronaut:
  application:
    name: crud
  server:
    port: 8000

---
datasources:
  default:
    url: jdbc:postgresql://localhost:26257/cindy
    driverClassName: org.postgresql.Driver
    username: root
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update



